"""
interview_engine.py – Lightweight in-memory state manager for a single interview session.
"""

from typing import Optional


class InterviewEngine:
    """
    Tracks the list of questions, the current position, and any pending
    follow-up question for a single interview session.
    """

    def __init__(self, questions: list):
        """
        Args:
            questions: Ordered list of question dicts generated by LLMQuestionGenerator.
        """
        self.questions: list = questions
        self.current_index: int = 0
        self._pending_follow_up: Optional[str] = None

    # ------------------------------------------------------------------
    # Question navigation
    # ------------------------------------------------------------------

    def get_current_question(self) -> Optional[dict]:
        """Return the current question dict, or None if the interview is finished."""
        if self.current_index < len(self.questions):
            return self.questions[self.current_index]
        return None

    def get_next_question(self) -> Optional[dict]:
        """
        Advance to the next main question and return it.
        If a follow-up is pending it should be retrieved first via
        get_and_clear_follow_up() before calling this method.
        """
        self.current_index += 1
        return self.get_current_question()

    def is_finished(self) -> bool:
        """Return True when all questions have been asked."""
        return self.current_index >= len(self.questions)

    # ------------------------------------------------------------------
    # Follow-up management
    # ------------------------------------------------------------------

    def set_follow_up(self, follow_up_text: str) -> None:
        """Store a pending follow-up question."""
        self._pending_follow_up = follow_up_text

    def get_and_clear_follow_up(self) -> Optional[str]:
        """
        Return the pending follow-up text (if any) and clear the slot.
        Returns None if no follow-up is pending.
        """
        fu = self._pending_follow_up
        self._pending_follow_up = None
        return fu

    def has_follow_up(self) -> bool:
        """Return True if a follow-up question is waiting to be asked."""
        return self._pending_follow_up is not None

    def clear_follow_up_if_any(self) -> None:
        """Discard any pending follow-up (no-op if none)."""
        self._pending_follow_up = None

    # ------------------------------------------------------------------
    # Progress info
    # ------------------------------------------------------------------

    def progress(self) -> dict:
        """Return a simple progress snapshot."""
        return {
            "current": self.current_index + 1,
            "total": len(self.questions),
            "finished": self.is_finished(),
        }
